# This is a basic workflow to help you get started with Actions

name: CI_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Print DIR
        shell: PowerShell
        run: ls
        
      - name: Dowload merkely
        shell: PowerShell
        run: wget "https://github.com/merkely-development/cli/releases/download/v1.5.0/merkely_1.5.0_windows_amd64.zip" -outfile "merkely_1.5.0_windows_amd64.zip"
      
      - name: Print DIR again
        shell: PowerShell
        run: ls
        
      - name: Print DIR in CMD
        shell: cmd
        run: dir
